# instance configuration for template 'metric'
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
 name: requestcount
 namespace: istio-system
spec:
 template: metric
 params:
   value: "1"
   dimensions:
    source_service: source.labels["app"] | source.service | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_service: destination.labels["app"] | destination.service | destination.service.host | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    response_code: response.code | 200
---
# handler configuration for adapter 'metric'
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: cloudmonitorhandler
 namespace: istio-system
spec:
 adapter: cloudmonitor
 connection:
   address: "[::]:61464" #replaces at runtime by the test
 params:
   regiond_id: cn-hangzhou
   access_key_id:
   access_key_secret:
   group_id: 100000
---
# rule to dispatch to your handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: mysamplerule
 namespace: istio-system
spec:
 actions:
 - handler: cloudmonitorhandler.istio-system
   instances:
   - requestcount
